# Generated by Django 5.1.1 on 2024-09-07 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DicomFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=255)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DicomTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('vr', models.CharField(max_length=10)),
                ('value', models.TextField()),
                ('dicom_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='dicom_app.dicomfile')),
            ],
        ),
    ]
