# Generated by Django 5.1.1 on 2025-03-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicomfile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
