# Generated by Django 5.1.1 on 2025-11-28 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_app', '0002_dicomtag_dicom_app_d_tag_680663_idx_and_more'),
        ('dicom_app', '0004_experiment_dicomfile_is_anonymized_participant_and_more'),
    ]

    operations = [
    ]
