# Generated by Django 5.1.1 on 2025-12-02 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_app', '0007_seed_initial_data'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='dicomtag',
            name='dicom_app_d_tag_680663_idx',
        ),
        migrations.RemoveIndex(
            model_name='dicomtag',
            name='dicom_app_d_dicom_f_f63741_idx',
        ),
    ]
