# Generated by Django 5.1.1 on 2025-12-04 18:19

from django.db import migrations


def fix_dicom_file_paths(apps, schema_editor):
    """
    Corrige las rutas de archivos DICOM existentes.
    Cambia de 'media/dicoms/raw/...' a 'dicoms/raw/...'
    """
    DicomFile = apps.get_model('dicom_app', 'DicomFile')
    
    for dicom_file in DicomFile.objects.all():
        if dicom_file.file and dicom_file.file.name.startswith('media/'):
            # Remover el prefijo 'media/'
            new_path = dicom_file.file.name.replace('media/', '', 1)
            dicom_file.file.name = new_path
            dicom_file.save(update_fields=['file'])
            print(f"Fixed path for DicomFile {dicom_file.id}: {new_path}")


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_app', '0010_alter_dicomfile_file'),
    ]

    operations = [
        migrations.RunPython(fix_dicom_file_paths, reverse_code=migrations.RunPython.noop),
    ]
