# Generated by Django 5.1.1 on 2025-04-22 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_app', '0002_alter_dicomfile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicomfile',
            name='file',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
    ]
