# Generated by Django 5.1.1 on 2025-12-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_app', '0005_merge_20251128_1102'),
    ]

    operations = [
        # Create Member model
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        # Remove indexes that may be causing issues
        migrations.RunSQL(
            sql="DROP INDEX IF EXISTS dicom_app_d_tag_680663_idx;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="DROP INDEX IF EXISTS dicom_app_d_dicom_f_f63741_idx;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Nullify all participant references in DicomFile
        migrations.RunSQL(
            sql="UPDATE dicom_app_dicomfile SET participant_id = NULL;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Delete all participants
        migrations.RunSQL(
            sql="DELETE FROM dicom_app_participant;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Drop the foreign key constraint
        migrations.RunSQL(
            sql="ALTER TABLE dicom_app_participant DROP CONSTRAINT IF EXISTS dicom_app_participant_experiment_id_fkey CASCADE;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Drop the experiment_id column
        migrations.RunSQL(
            sql="ALTER TABLE dicom_app_participant DROP COLUMN IF EXISTS experiment_id;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Add new fields to participant
        migrations.RunSQL(
            sql="ALTER TABLE dicom_app_participant ADD COLUMN IF NOT EXISTS email VARCHAR(254) DEFAULT '';",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="ALTER TABLE dicom_app_participant ADD COLUMN IF NOT EXISTS first_name VARCHAR(100) DEFAULT '';",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="ALTER TABLE dicom_app_participant ADD COLUMN IF NOT EXISTS last_name VARCHAR(100) DEFAULT '';",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="ALTER TABLE dicom_app_participant ADD COLUMN IF NOT EXISTS phone VARCHAR(20) DEFAULT '';",
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Make subject_id unique
        migrations.RunSQL(
            sql="ALTER TABLE dicom_app_participant ADD CONSTRAINT dicom_app_participant_subject_id_unique UNIQUE (subject_id);",
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Create the many-to-many table for participant-experiment relationship
        migrations.RunSQL(
            sql="""
            CREATE TABLE IF NOT EXISTS dicom_app_participant_experiments (
                id BIGSERIAL PRIMARY KEY,
                participant_id BIGINT NOT NULL REFERENCES dicom_app_participant(id) ON DELETE CASCADE,
                experiment_id BIGINT NOT NULL REFERENCES dicom_app_experiment(id) ON DELETE CASCADE,
                UNIQUE (participant_id, experiment_id)
            );
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Create the many-to-many table for member-experiment relationship
        migrations.RunSQL(
            sql="""
            CREATE TABLE IF NOT EXISTS dicom_app_member_experiments (
                id BIGSERIAL PRIMARY KEY,
                member_id BIGINT NOT NULL REFERENCES dicom_app_member(id) ON DELETE CASCADE,
                experiment_id BIGINT NOT NULL REFERENCES dicom_app_experiment(id) ON DELETE CASCADE,
                UNIQUE (member_id, experiment_id)
            );
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Update Django's state to match the database
        migrations.RemoveField(
            model_name='participant',
            name='experiment',
        ),
        migrations.AddField(
            model_name='participant',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='participant',
            name='experiments',
            field=models.ManyToManyField(blank=True, related_name='participants', to='dicom_app.experiment'),
        ),
        migrations.AddField(
            model_name='participant',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='participant',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='participant',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='participant',
            name='subject_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='member',
            name='experiments',
            field=models.ManyToManyField(blank=True, related_name='members', to='dicom_app.experiment'),
        ),
    ]
