# Generated by Django 5.1.1 on 2025-12-02 12:52

from django.db import migrations


def seed_participants_and_members(apps, schema_editor):
    """Seed initial data for Participants and Members"""
    Participant = apps.get_model('dicom_app', 'Participant')
    Member = apps.get_model('dicom_app', 'Member')
    
    # Create 10 Participants with fictional data
    participants_data = [
        {'subject_id': 'PART001', 'first_name': 'Juan', 'last_name': 'García', 'email': 'juan.garcia@example.com', 'phone': '+54 11 1234-5678'},
        {'subject_id': 'PART002', 'first_name': 'María', 'last_name': 'Rodríguez', 'email': 'maria.rodriguez@example.com', 'phone': '+54 11 2345-6789'},
        {'subject_id': 'PART003', 'first_name': 'Carlos', 'last_name': 'López', 'email': 'carlos.lopez@example.com', 'phone': '+54 11 3456-7890'},
        {'subject_id': 'PART004', 'first_name': 'Ana', 'last_name': 'Martínez', 'email': 'ana.martinez@example.com', 'phone': '+54 11 4567-8901'},
        {'subject_id': 'PART005', 'first_name': 'Luis', 'last_name': 'Fernández', 'email': 'luis.fernandez@example.com', 'phone': '+54 11 5678-9012'},
        {'subject_id': 'PART006', 'first_name': 'Laura', 'last_name': 'González', 'email': 'laura.gonzalez@example.com', 'phone': '+54 11 6789-0123'},
        {'subject_id': 'PART007', 'first_name': 'Diego', 'last_name': 'Pérez', 'email': 'diego.perez@example.com', 'phone': '+54 11 7890-1234'},
        {'subject_id': 'PART008', 'first_name': 'Sofía', 'last_name': 'Sánchez', 'email': 'sofia.sanchez@example.com', 'phone': '+54 11 8901-2345'},
        {'subject_id': 'PART009', 'first_name': 'Miguel', 'last_name': 'Ramírez', 'email': 'miguel.ramirez@example.com', 'phone': '+54 11 9012-3456'},
        {'subject_id': 'PART010', 'first_name': 'Valentina', 'last_name': 'Torres', 'email': 'valentina.torres@example.com', 'phone': '+54 11 0123-4567'},
    ]
    
    for data in participants_data:
        Participant.objects.create(**data)
    
    # Create 10 Members with fictional data
    members_data = [
        {'first_name': 'Roberto', 'last_name': 'Silva', 'role': 'Líder Científico/a', 'email': 'roberto.silva@hospital.com'},
        {'first_name': 'Patricia', 'last_name': 'Morales', 'role': 'Coordinador/a de Investigación', 'email': 'patricia.morales@hospital.com'},
        {'first_name': 'Fernando', 'last_name': 'Castro', 'role': 'Técnico/a en Neuroimagen', 'email': 'fernando.castro@hospital.com'},
        {'first_name': 'Gabriela', 'last_name': 'Vargas', 'role': 'Neurólogo/a', 'email': 'gabriela.vargas@hospital.com'},
        {'first_name': 'Andrés', 'last_name': 'Mendoza', 'role': 'Bioestadístico/a o Científico/a de Datos', 'email': 'andres.mendoza@hospital.com'},
        {'first_name': 'Carolina', 'last_name': 'Rojas', 'role': 'Co-investigador/a', 'email': 'carolina.rojas@hospital.com'},
        {'first_name': 'Javier', 'last_name': 'Ortiz', 'role': 'Bioestadístico/a o Científico/a de Datos', 'email': 'javier.ortiz@hospital.com'},
        {'first_name': 'Daniela', 'last_name': 'Herrera', 'role': 'Asistente de Investigación', 'email': 'daniela.herrera@hospital.com'},
        {'first_name': 'Martín', 'last_name': 'Navarro', 'role': 'Ingeniero/a Biomédico/a', 'email': 'martin.navarro@hospital.com'},
        {'first_name': 'Lucía', 'last_name': 'Campos', 'role': 'Coordinador/a Clínico', 'email': 'lucia.campos@hospital.com'},
    ]
    
    for data in members_data:
        Member.objects.create(**data)

    # Create 5 Experiments
    Experiment = apps.get_model('dicom_app', 'Experiment')
    experiments_data = [
        {'name': 'Estudio de Resonancia Magnética Cerebral', 'description': 'Análisis de estructuras corticales en pacientes con migraña crónica.', 'status': 'Active'},
        {'name': 'Tomografía de Tórax - COVID-19', 'description': 'Evaluación de secuelas pulmonares post-COVID mediante TAC de alta resolución.', 'status': 'Active'},
        {'name': 'Ecografía Doppler Cardíaca', 'description': 'Estudio de flujo sanguíneo valvular en pacientes hipertensos.', 'status': 'Active'},
        {'name': 'Resonancia de Rodilla - Meniscos', 'description': 'Evaluación de lesiones meniscales en deportistas de alto rendimiento.', 'status': 'Active'},
        {'name': 'PET-CT Oncológico', 'description': 'Seguimiento de respuesta al tratamiento en pacientes con linfoma.', 'status': 'Active'},
    ]

    import random
    all_participants = list(Participant.objects.all())
    all_members = list(Member.objects.all())

    for exp_data in experiments_data:
        experiment = Experiment.objects.create(**exp_data)
        
        # Add random participants (2-5 per experiment)
        if all_participants:
            experiment.participants.add(*random.sample(all_participants, k=min(len(all_participants), random.randint(2, 5))))
        
        # Add random members (2-4 per experiment)
        if all_members:
            experiment.members.add(*random.sample(all_members, k=min(len(all_members), random.randint(2, 4))))


def reverse_seed(apps, schema_editor):
    """Remove seeded data"""
    Participant = apps.get_model('dicom_app', 'Participant')
    Member = apps.get_model('dicom_app', 'Member')
    
    # Delete seeded participants
    Participant.objects.filter(subject_id__startswith='PART').delete()
    
    # Delete seeded members
    Member.objects.filter(email__endswith='@hospital.com').delete()

    # Delete seeded experiments
    Experiment = apps.get_model('dicom_app', 'Experiment')
    Experiment.objects.filter(status='Active').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_app', '0006_member_remove_dicomtag_dicom_app_d_tag_680663_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_participants_and_members, reverse_seed),
    ]
