# Generated by Django 5.1.1 on 2025-12-03 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_app', '0009_dicomfile_experiment_dicomfile_file_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicomfile',
            name='file',
            field=models.FileField(upload_to='dicoms/raw/%Y/%m/%d/'),
        ),
    ]
