# Generated by Django 5.1.1 on 2025-12-05 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_app', '0012_update_member_roles_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('Líder Científico/a', 'Líder Científico/a'), ('Co-investigador/a', 'Co-investigador/a'), ('Investigador/a Posdoctoral', 'Investigador/a Posdoctoral'), ('Coordinador/a de Investigación', 'Coordinador/a de Investigación'), ('Coordinador/a Clínico', 'Coordinador/a Clínico'), ('Neurólogo/a', 'Neurólogo/a'), ('Técnico/a en Neuroimagen', 'Técnico/a en Neuroimagen'), ('Ingeniero/a Biomédico/a', 'Ingeniero/a Biomédico/a'), ('Especialista en Procesamiento de Imágenes', 'Especialista en Procesamiento de Imágenes'), ('Asistente de Investigación', 'Asistente de Investigación'), ('Bioestadístico/a o Científico/a de Datos', 'Bioestadístico/a o Científico/a de Datos')], max_length=100),
        ),
    ]
